/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carnet.adresse;

import carnet.adresse.verifier.*;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Hp
 */
public class Main extends javax.swing.JFrame {
    
    private DefaultTableModel m;
    private File fichier;
    /**
     * Creates new form Main
     * @throws java.sql.SQLException
     */
    public Main() throws SQLException {
        initComponents();
        fichier = new File("produits.tmp");
        m = (DefaultTableModel) annuaire.getModel();
        this.fillTable();
        modifierBtn.setEnabled(false);
        suppBtn.setEnabled(false);
        
        numeroInput.setInputVerifier(new NumeroVerifier());
    }
    
    public void fillTable() {
        for(Produit p : FileManager.lire(fichier)) {
            m.addRow(p.toObject());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        numeroLabel = new javax.swing.JLabel();
        numeroInput = new javax.swing.JTextField();
        categorieLabel = new javax.swing.JLabel();
        categorieInput = new javax.swing.JComboBox<>();
        libelleLabel = new javax.swing.JLabel();
        libelleInput = new javax.swing.JTextField();
        prixlLabel = new javax.swing.JLabel();
        prixInput = new javax.swing.JTextField();
        datePeremption = new javax.swing.JLabel();
        dateInput = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        ajouterBtn = new javax.swing.JButton();
        modifierBtn = new javax.swing.JButton();
        suppBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        searchInput = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        annuaire = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_product_48px.png"))); // NOI18N
        jLabel1.setText("Stock de Produits");

        jPanel2.setLayout(new java.awt.GridLayout(5, 4, 0, 20));

        numeroLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        numeroLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeroLabel.setText("Numéro");
        jPanel2.add(numeroLabel);

        numeroInput.setBackground(new java.awt.Color(204, 204, 204));
        numeroInput.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        numeroInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(numeroInput);

        categorieLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        categorieLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        categorieLabel.setText("Catégorie");
        jPanel2.add(categorieLabel);

        categorieInput.setBackground(new java.awt.Color(204, 204, 204));
        categorieInput.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        categorieInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "alimentaire", "santé", "beauté" }));
        categorieInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorieInputActionPerformed(evt);
            }
        });
        jPanel2.add(categorieInput);

        libelleLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        libelleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        libelleLabel.setText("Libelle");
        jPanel2.add(libelleLabel);

        libelleInput.setBackground(new java.awt.Color(204, 204, 204));
        libelleInput.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        libelleInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(libelleInput);

        prixlLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        prixlLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prixlLabel.setText("Prix Unitaire");
        jPanel2.add(prixlLabel);

        prixInput.setBackground(new java.awt.Color(204, 204, 204));
        prixInput.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        prixInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prixInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prixInputActionPerformed(evt);
            }
        });
        jPanel2.add(prixInput);

        datePeremption.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        datePeremption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        datePeremption.setText("Date de Péremption");
        jPanel2.add(datePeremption);

        dateInput.setBackground(new java.awt.Color(204, 204, 204));
        dateInput.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        dateInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(dateInput);

        jPanel3.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        jPanel4.setLayout(new java.awt.GridLayout(1, 5, 5, 0));

        ajouterBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        ajouterBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_checkmark_26px.png"))); // NOI18N
        ajouterBtn.setText("Ajouter");
        ajouterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterBtnActionPerformed(evt);
            }
        });
        jPanel4.add(ajouterBtn);

        modifierBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        modifierBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_update_left_rotation_24px.png"))); // NOI18N
        modifierBtn.setText("Modifier");
        modifierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierBtnActionPerformed(evt);
            }
        });
        jPanel4.add(modifierBtn);

        suppBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        suppBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_delete_30px.png"))); // NOI18N
        suppBtn.setText("Supprimer");
        suppBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppBtnActionPerformed(evt);
            }
        });
        jPanel4.add(suppBtn);

        cancelBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_delete_sign_30px.png"))); // NOI18N
        cancelBtn.setText("Annuler");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        jPanel4.add(cancelBtn);

        jPanel5.setLayout(new java.awt.BorderLayout());

        searchInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchInputKeyReleased(evt);
            }
        });
        jPanel5.add(searchInput, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        annuaire.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        annuaire.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Catégorie", "Libelle", "Prix Unitaire", "Date de Péremption"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        annuaire.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                annuaireFocusLost(evt);
            }
        });
        annuaire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                annuaireMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(annuaire);

        jPanel6.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(270, 270, 270))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prixInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prixInputActionPerformed
        
    }//GEN-LAST:event_prixInputActionPerformed

    private void ajouterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterBtnActionPerformed
        Produit p = new Produit(numeroInput.getText(), categorieInput.getSelectedItem().toString(), libelleInput.getText(), prixInput.getText(), dateInput.getText());
        fichier = FileManager.ajoutPersonne(p, fichier);
        m.addRow(p.toObject());
        reset();
//        JOptionPane.showMessageDialog(this, p.getNom() + " " + p.getPrenom() + "a été bien ajouté.");
    }//GEN-LAST:event_ajouterBtnActionPerformed

    private void modifierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierBtnActionPerformed
        int row = annuaire.getSelectedRow();
        Produit p = getSelectedProduit();
        if (p != null) {
            p.setNumero(numeroInput.getText());
            p.setCategorie(categorieInput.getSelectedItem().toString());
            p.setLibelle(libelleInput.getText());
            p.setPrixUnitaire(prixInput.getText());
            p.setDatePeremption(dateInput.getText());
            m.removeRow(row);
            m.insertRow(row, p.toObject());
            fichier = FileManager.update(row, p, fichier);
//            JOptionPane.showMessageDialog(this, p.getNom() + " " + p.getPrenom() + "a été bien modifié.");
        }
        reset();
    }//GEN-LAST:event_modifierBtnActionPerformed

    private void annuaireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annuaireMouseClicked
        Produit p = getSelectedProduit();
        if (p != null) {
            numeroInput.setText(p.getNumero());
//            categorieInput.set(p.getPrenom());
            libelleInput.setText(p.getLibelle());
            prixInput.setText(p.getPrixUnitaire());
            dateInput.setText(p.getDatePeremption());
            modifierBtn.setEnabled(true);
            suppBtn.setEnabled(true);
        }
    }//GEN-LAST:event_annuaireMouseClicked

    private void suppBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppBtnActionPerformed
        int row = annuaire.getSelectedRow();
        Produit p = getSelectedProduit();
        int i = JOptionPane.showConfirmDialog(this, "Voulez vous réellement supprimer cette produit ?");
        System.out.println(i);
        if (p != null && i == JOptionPane.OK_OPTION) {
            fichier = FileManager.remove(row, fichier);
            m.removeRow(row);
            System.out.println("DELETED : " + p);
        }
        reset();
    }//GEN-LAST:event_suppBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        reset();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void annuaireFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_annuaireFocusLost
//        modifierBtn.setEnabled(false);
//        suppBtn.setEnabled(false);
    }//GEN-LAST:event_annuaireFocusLost

    private void searchInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchInputKeyReleased
        List<RowFilter<Object, Object>> rf = new ArrayList();
        TableRowSorter<TableModel> sorter = new TableRowSorter(annuaire.getModel());
        annuaire.setRowSorter(sorter);
        rf.add(RowFilter.regexFilter("(?i)" + searchInput.getText(), 0));
        RowFilter<Object, Object> andFilter = RowFilter.andFilter(rf);
        sorter.setRowFilter(andFilter);
//        System.out.println(searchInput.getText());
    }//GEN-LAST:event_searchInputKeyReleased

    private void categorieInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorieInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categorieInputActionPerformed
    
    private void reset() {
        numeroInput.setText("");
        libelleInput.setText("");
        prixInput.setText("");
        dateInput.setText("");
    }
    
    private Produit getSelectedProduit() {
        Produit p = null;
        int row = annuaire.getSelectedRow();
        if (row != -1)
            p = FileManager.lire(fichier).get(row);
        System.out.println("Personne selectionnée : " + p);
        return p;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterBtn;
    private javax.swing.JTable annuaire;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<String> categorieInput;
    private javax.swing.JLabel categorieLabel;
    private javax.swing.JTextField dateInput;
    private javax.swing.JLabel datePeremption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField libelleInput;
    private javax.swing.JLabel libelleLabel;
    private javax.swing.JButton modifierBtn;
    private javax.swing.JTextField numeroInput;
    private javax.swing.JLabel numeroLabel;
    private javax.swing.JTextField prixInput;
    private javax.swing.JLabel prixlLabel;
    private javax.swing.JTextField searchInput;
    private javax.swing.JButton suppBtn;
    // End of variables declaration//GEN-END:variables
}
